name: Android CI
on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      -  name: Set-up JDK 11
         uses: actions/setup-java@v3
         with:
             java-version: '11'
             distribution: 'temurin'
             cache: gradle
         
      -  name: Grant execute permission for gradlew
         run: chmod +x gradlew
         
      -  name: Run Tests
         run: ./gradlew test
         
#      -  name: Build Release Apk
#         run: ./gradlew assembleRelease

      - name:  Build Signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore_b64: ${{ secrets.GIT_JKS_FILE }}
          key_alias: ${{ secrets.GIT_KEY_ALIAS }}
          keystore_password: ${{ secrets.GIT_STORE_PASSWORD }}
          key_password: ${{ secrets.GIT_KEY_PASSWORD }}

      - name: Upload our APK
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Release artifact
          path: app/build/outputs/apk/release/app-release.apk

        
