name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-sign-apk:
    name: Build and Sign APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set tag output
        id: set_tag_output
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build Release APK
        id: build
        run: ./gradlew assembleRelease

      - name: Sign Release APK
        id: sign_apk
        uses: victorbnl/build-signed-apk@main
        with:
          keystore_b64: ${{ secrets.GIT_JKS_FILE }}
          key_alias: ${{ secrets.GIT_KEY_ALIAS }}
          keystore_password: ${{ secrets.GIT_STORE_PASSWORD }}
          key_password: ${{ secrets.GIT_KEY_PASSWORD }}

      - name: Make artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release-signed
          path: ${{ steps.sign_apk.outputs.signedReleaseFile }}

      - name: Build Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v3
        with:
          version: ${{ env.TAG_NAME }}
          exclude-tags: 'rc*'
          tag-pattern: 'v*'
          remove-links: true
          date-format: '%Y-%m-%d'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.sign_apk.outputs.signedReleaseFile }}
          asset_name: app-release-signed-${{ env.TAG_NAME }}.apk
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
