name: Android CI
on:
  pull_request:
    branches: [ master ]

jobs:
  Build:
    name: Build/Sign APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > app/keystore.jks
      - name: Build Release apk
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Remove keystore file
        run: rm app/keystore.jks

      - name: Make artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-signed
          path: app/build/outputs/apk/release

  Release:
    name: Create Release/Upload APK
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-release-signed
          path: app/build/outputs/apk/release

      - name: Expose version name
        uses: michpohl/android-expose-version-name-action@v1.0.0
        with:
          expose-version-name: 'true'
          expose-version-code: 'true'

      - name: Install github_changelog_generator
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-dev
          sudo gem install github_changelog_generator

      - name: Generate Changelog
        id: generate_changelog
        env:
          ANDROID_VERSION_NAME: ${{ env.ANDROID_VERSION_NAME }}
        run: |
          PREVIOUS_ANDROID_VERSION_NAME=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | grep -B1 "$ANDROID_VERSION_NAME" | tail -n1)
          echo "Previous version: $PREVIOUS_ANDROID_VERSION_NAME"
          mkdir -p build
          github_changelog_generator \
            --since-tag $PREVIOUS_ANDROID_VERSION_NAME \
            --output build/changelog.md
          changelog=$(cat build/changelog.md)
          echo "::set-output name=changelog::$changelog"

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: false
          prerelease: false
          files: |
            app/build/outputs/apk/release/app-release.apk
          tag_name: ${{ env.ANDROID_VERSION_NAME }}
          name: Release ${{ env.ANDROID_VERSION_NAME }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
