#name: Android CI
#on:
#  pull_request:
#    branches: [ master ]
#
#jobs:
#  Build:
#    name: Build/Sign APK
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          distribution: temurin
#          java-version: 11
#
#      - name: Grant Permission to Execute Gradle
#        run: chmod +x gradlew
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#
#      - name: Build test library
#        run: ./gradlew teslibrary:assembleRelease
#
#      - name: Publish packages test library
#        if: github.event.pull_request.merged == true
#        env:
#          GIT_NAME_TEST: ${{ secrets.GIT_NAME_TEST }}
#          GIT_TOKEN_TEST: ${{ secrets.GIT_TOKEN_TEST }}
#        run: ./gradlew publish
#
#
#
##      - name: Remove keystore file
##        run: rm app/keystore.jks
##
##      - name: Make artifact
##        uses: actions/upload-artifact@v3
##        with:
##          name: app-release-signed
##          path: app/build/outputs/apk/release
##
##
##
##      - name: Make artifact
##        uses: actions/upload-artifact@v3
##        with:
##          name: app-release-signed
##          path: app/build/outputs/apk/release
#
##  Release:
##    name: Create Release/Upload APK
##    needs: Build
##    runs-on: ubuntu-latest
##    steps:
##      - uses: actions/checkout@v3
##
##      - name: Download artifact
##        uses: actions/download-artifact@v3
##        with:
##          name: app-release-signed
##          path: app/build/outputs/apk/release
##
##      - name: Expose version name
##        uses: michpohl/android-expose-version-name-action@v1.0.0
##        with:
##          expose-version-name: 'true'
##          expose-version-code: 'true'
##
##      - name: Install github_changelog_generator
##        run: |
##          sudo apt-get update
##          sudo apt-get install -y ruby-dev
##          sudo gem install github_changelog_generator
##
##      - name: Get last commit message
##        id: last_commit
##        run: |
##          last_commit_message=$(git log --no-merges -1 --pretty=format:%s)
##          echo "last_commit_message=$last_commit_message" >> $GITHUB_ENV
##
##      - name: Create Github Release
##        uses: softprops/action-gh-release@v1
##        with:
##          generate_release_notes: false
##          prerelease: false
##          files: |
##            app/build/outputs/apk/release/app-release.apk
##          tag_name: ${{ env.ANDROID_VERSION_NAME }}
##          name: Release ${{ env.ANDROID_VERSION_NAME }}
##          body: |
##            # new changes have been made
##            ${{ env.last_commit_message }}
##        env:
##          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
