name: Android CI
on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
        
      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
           java-version: 11
           
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Build
        run: ./gradlew build
        
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.1
        with:
          name: artifact_apk
          path: app/build/outputs/apk/debug/app-debug.apk

        
