name: Android CI
on:
  pull_request:
    branches: [ master ]

jobs:
  Build:
    name: Build/Sign APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > app/keystore.jks
      - name: Build Release apk
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Remove keystore file
        run: rm app/keystore.jks

      - name: Make artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-signed
          path: app/build/outputs/apk/release

  Release:
    name: Create Release/Upload APK
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-release-signed
          path: app/build/outputs/apk/release

      - name: Expose version name
        uses: michpohl/android-expose-version-name-action@v1.0.0
        with:
          expose-version-name: 'true'
          expose-version-code: 'true'

      #      - name: Generate Changelog
      #        id: generate_changelog
      #        run: |
      #          changelog=""
      #          for commit in $(git log --format="%H" --reverse ${{ github.event.before }}..${{ github.event.after }})
      #          do
      #            COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s" $commit)
      #            COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an" $commit)
      #            COMMIT_DATE=$(git log -1 --pretty=format:"%ad" $commit)
      #            changelog="$changelog\nCommit: $commit\nMessage: $COMMIT_MESSAGE\nAuthor: $COMMIT_AUTHOR\nDate: $COMMIT_DATE\n\n"
      #          done
      #          echo "::set-output name=changelog::$changelog"

      - name: Install git-chglog
        run: |
          curl -L https://github.com/git-chglog/git-chglog/releases/download/v0.15.0/git-chglog_0.15.0_linux_amd64.tar.gz -o git-chglog.tar.gz
          tar -zxvf git-chglog.tar.gz
          sudo mv git-chglog /usr/local/bin

      - name: Generate Changelog
        id: generate_changelog
        run: |
          git-chglog --output CHANGELOG.md
          changelog=$(cat CHANGELOG.md)
          echo "changelog=$changelog" >> $GITHUB_ENV

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: false
          prerelease: false
          files: |
            app/build/outputs/apk/release/app-release.apk
          tag_name: ${{ env.ANDROID_VERSION_NAME }}
          name: Release ${{ env.ANDROID_VERSION_NAME }}
          body: ${{ env.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



#      - name: Upload APK
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: app/build/outputs/apk/release/app-release.apk
#          asset_name: app-release-signed-${{ env.ANDROID_VERSION_NAME }}.apk
#          asset_content_type: application/zip
