name: Android CI
on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      -  name: Set-up JDK 11
         uses: actions/setup-java@v3
         with:
             java-version: '11'
             distribution: 'temurin'
             cache: gradle
         
      -  name: Grant execute permission for gradlew
         run: chmod +x gradlew
         
      -  name: Run Tests
         run: ./gradlew test
         
      -  name: Build Release Apk
         run: ./gradlew assembleRelease

      - name: Sign Release Artifact
        id: signArtifact
        uses: r0adkll/sign-android-release@v2.2.1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.GIT_JKS_FILE }}
          alias: ${{ secrets.GIT_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.GIT_STORE_PASSWORD }}
          keyPassword: ${{ secrets.GIT_KEY_PASSWORD }}

      - name: Upload our APK
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Release artifact
          path: app/build/outputs/apk/release/app-release.apk

        
