name: Publish on Merge
on:
  pull_request:
    branches: [ master ]

jobs:
  Publish:
    name: Publish packages test library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build test library
        run: ./gradlew teslibrary:assembleRelease

      - name: Publish packages test library
        env:
          GIT_NAME_TEST: ${{ secrets.GIT_NAME_TEST }}
          GIT_TOKEN_TEST: ${{ secrets.GIT_TOKEN_TEST }}
        run: ./gradlew publish

      - name: Expose version name
        uses: michpohl/android-expose-version-name-action@v1.0.0
        with:
          expose-version-name: 'true'
          expose-version-code: 'true'

      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: false
          prerelease: false
          files: |
            app/build/outputs/aar/teslibrary-release.aar
          tag_name: '0.0.6'
          name: 'Release 0.0.6'
          body: |
            ${{ steps.Changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}